spring.application.name=SriLankaRailways

# SQL Server Database
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=SriLankaRailwaysDB;integratedSecurity=true;encrypt=true;trustServerCertificate=true

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080