spring.application.name=train-booking
server.port=8080

# Microsoft SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=train_booking;encrypt=true;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# CHANGE THESE to your actual SSMS login details:
spring.datasource.username=sa
spring.datasource.password=sql123

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update